### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by slomo** [policycompass/policycompass-fcmmanager#8]
Currently the fcmmanager doesn't compile because org.megadix.jfcm:jfcm-core:jar:1.4.1 was added as dependency which is not available on maven central.

**Comment by slomo** [comment]
As a reference see the travis build of the main repository https://travis-ci.org/policycompass/policycompass/builds/65056723

**Comment by belalakbar** [comment]
Updated the installation process for JFCM, please see
https://github.com/policycompass/policycompass-fcmmanager/blob/master/README.md

**Comment by slomo** [comment]
Well that might fix the issue ... but it also a hurdle for installation. Can't you either nag the JCFM author to put his stuff onto maven or put it yourself on maven?

(I just opened a ticket with jcfm lets see what they say)

**Comment by slomo** [comment]
@belalakbar Please have look on the reference issue. After changing the JCFM dependencie to

```
    <!-- JFCM -->
    <dependency>
      <groupId>com.github.megadix</groupId>
      <artifactId>jfcm</artifactId>
      <version>v1.4.2</version>
    </dependency>
```

And adding the jitpack repository, I was able to build fcm-manager again on my machine:

```
 <repositories>
    <repository>
     <id>jitpack.io</id>
     <url>https://jitpack.io</url>
    </repository>
  </repositories>
```

**Comment by slomo** [comment]
Please update this quickly ... it is the only thing that breaks our travis build currently and it is very annoying.

**Comment by slomo** [comment]
Nevermind, I just fixed it myself.
